// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9_K8Vv5OKF-qJdolpd1pc2XUoHVlNaVw',
    appId: '1:711565955650:web:e81c8b21b5ae759a3093db',
    messagingSenderId: '711565955650',
    projectId: 'spography-trivial',
    authDomain: 'spography-trivial.firebaseapp.com',
    storageBucket: 'spography-trivial.firebasestorage.app',
    measurementId: 'G-QDD8MJ3WMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqjTp-lgV_n-CQKQMJaZp0ayjcBfqygKY',
    appId: '1:711565955650:android:c4ed47a59f89eb2f3093db',
    messagingSenderId: '711565955650',
    projectId: 'spography-trivial',
    storageBucket: 'spography-trivial.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjeGpK0r_ZtDZVjz5LDTch5PgDCirAfB4',
    appId: '1:711565955650:ios:74d295baeaab5cca3093db',
    messagingSenderId: '711565955650',
    projectId: 'spography-trivial',
    storageBucket: 'spography-trivial.firebasestorage.app',
    iosBundleId: 'com.example.spographyTrivial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjeGpK0r_ZtDZVjz5LDTch5PgDCirAfB4',
    appId: '1:711565955650:ios:74d295baeaab5cca3093db',
    messagingSenderId: '711565955650',
    projectId: 'spography-trivial',
    storageBucket: 'spography-trivial.firebasestorage.app',
    iosBundleId: 'com.example.spographyTrivial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9_K8Vv5OKF-qJdolpd1pc2XUoHVlNaVw',
    appId: '1:711565955650:web:d69c0d37223b48fd3093db',
    messagingSenderId: '711565955650',
    projectId: 'spography-trivial',
    authDomain: 'spography-trivial.firebaseapp.com',
    storageBucket: 'spography-trivial.firebasestorage.app',
    measurementId: 'G-FRBMKW4PNB',
  );
}
